name: rps_env
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python == 3.10
  - numpy
  - matplotlib
  - pillow
  - scikit-learn
  - pandas
  - seaborn
  - requests
  - ipykernel
  - tqdm
  - pip
  - pip:
      - tensorflow
      - streamlit
      - opencv-python
