name: rps_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python == 3.10
  - numpy
  - matplotlib
  - pillow
  - scikit-learn
  - pandas
  - seaborn
  - requests
  - ipykernel
  - tqdm
  - plotly
  - pip
  - pip:
      - tensorflow==2.13.0
      - streamlit
      - opencv-python
      - tensorflow-datasets
      - streamlit-option-menu
      - watchdog